version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: MySQL
      MYSQL_DATABASE: E-Co Books
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations/01-books.sql:/docker-entrypoint-initdb.d/01-book.sql
      - ./migrations/02-user.sql:/docker-entrypoint-initdb.d/02-user.sql
      - ./migrations/03-order.sql:/docker-entrypoint-initdb.d/03-order.sql
      - ./migrations/04-cart.sql:/docker-entrypoint-initdb.d/04-cart.sql
      - ./migrations/05-payment.sql:/docker-entrypoint-initdb.d/05-payment.sql

  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: E-Co Books
      DB_USER: root
      DB_PASS: MySQL
      APP_PORT: 3000
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data: